return {
	title = "DiveLog",
	id = "diveLogTagset",
	items = {
		'com.adobe.title',
		{ 'com.adobe.caption', height_in_lines = 3 },
		'com.adobe.separator',
		{ 'com.adobe.label', label = "Date/time" },
		'com.adobe.dateTimeOriginal',
		'com.adobe.dateTimeDigitized',
		'com.adobe.dateTime',
		'com.adobe.separator',
		{ 'com.adobe.label', label = "Location" },
		'com.adobe.location',
		'com.adobe.city',
		'com.adobe.state',
		'com.adobe.country',
		'com.adobe.GPS',
		'com.adobe.GPSAltitude',
		'com.adobe.separator',
		{ 'com.adobe.label', label = "Dive log sync" },
		"us.hordur.divelogsync.id",
    "us.hordur.divelogsync.dive_number",
    "us.hordur.divelogsync.depth",
    "us.hordur.divelogsync.water_temperature",
    "us.hordur.divelogsync.run_time",
    "us.hordur.divelogsync.dive_site",
	},
}
